version: '3'
services:
  preparation_1:
    image: preparation
    build:
      context: ./preparation
      dockerfile: ./Dockerfile
    ports:
      - 5600:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/preprocesing.py 1 5600 192.168.0.14 0 5600 3 5700

  preparation_2:
    image: preparation
    build:
      context: ./preparation
      dockerfile: ./Dockerfile
    ports:
      - 5601:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/preprocesing.py 2 5601 192.168.0.14 0 5600 3 5700

  preparation_3:
    image: preparation
    build:
      context: ./preparation
      dockerfile: ./Dockerfile
    ports:
      - 5602:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/preprocesing.py 3 5602 192.168.0.14 0 5600 3 5700

  preparation_4:
    image: preparation
    build:
      context: ./preparation
      dockerfile: ./Dockerfile
    ports:
      - 5603:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/preprocesing.py 4 5603 192.168.0.14 1 5600 3 5700
  
  conquer:
    image: conquer
    build:
      context: ./conquer
      dockerfile: ./Dockerfile
    ports:
      - 5700:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/conquer.py 3 192.168.0.14 5700 

  loadbalance_k:
    image: loadbalance_k
    build:
      context: ./loadbalance_k
      dockerfile: ./Dockerfile
    ports:
      - 5701:5000
    networks:
       - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/app_k.py 2 192.168.0.14 5701 4000
  
  cbNodo_1_1:
    image: chord_bully
    build:
      context: ./cbNodo
      dockerfile: ./Dockerfile
    ports:
      - 4000:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/app.py 1 4000 192.168.0.14 0 4000 2
  
  cbNodo_1_2:
    image: chord_bully
    build:
      context: ./cbNodo
      dockerfile: ./Dockerfile
    ports:
      - 4001:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/app.py 2 4001 192.168.0.14 0 4000 2

  cbNodo_1_3:
    image: chord_bully
    build:
      context: ./cbNodo
      dockerfile: ./Dockerfile
    ports:
      - 4002:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/app.py 3 4002 192.168.0.14 1 4000 2
  
  cbNodo_2_1:
    image: chord_bully
    build:
      context: ./cbNodo
      dockerfile: ./Dockerfile
    ports:
      - 4100:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/app.py 1 4100 192.168.0.14 0 4100 2
  
  cbNodo_2_2:
    image: chord_bully
    build:
      context: ./cbNodo
      dockerfile: ./Dockerfile
    ports:
      - 4101:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/app.py 2 4101 192.168.0.14 0 4100 2

  cbNodo_2_3:
    image: chord_bully
    build:
      context: ./cbNodo
      dockerfile: ./Dockerfile
    ports:
      - 4102:5000
    networks:
      - clus_net
    volumes:
      - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
    command: python /app/app.py 3 4102 192.168.0.14 1 4100 2
  
  # cbNodo_5:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4004:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 5 4004 192.168.0.14 0 4000 2

  # cbNodo_6:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4005:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 6 4005 192.168.0.14 1 4000 2

  # cbNodo_7:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4006:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 7 4006 192.168.0.14 0 4000 2
  
  # cbNodo_8:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4007:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 8 4007 192.168.0.14 0 4000 2
  
  # cbNodo_9:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4008:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 9 4008 192.168.0.14 1 4000 2

  
  # cbNodo_10:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4009:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 10 4009 192.168.0.14 0 4000 2
  
  # cbNodo_11:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4010:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 11 4010 192.168.0.14 0 4000 2

  # cbNodo_12:
  #   image: chord_bully
  #   build:
  #     context: ./cbNodo
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4011:5000
  #   networks:
  #     - clus_net
  #   volumes:
  #     - /home/morin/Escritorio/Proyecto_Final_TSSD/Files/:/app/data/
  #   command: python /app/app.py 12 4011 192.168.0.14 1 4000 2

networks:
  clus_net:
